---
name: New Rule
about: Propose new rule

---

<!-- New rule you want to propose might have already be reported!
Please search in the [issues](https://github.com/pinterest/ktlint/issues) before creating one. -->

## Expected Rule behavior
<!-- Tell us what rule should check -->

## Additional information
* Current version of ktlint:
* Styleguide section: <!-- link should cover expected rule behaviour -->
